
remote_theme: christianezeani/panthera-jekyll

title: GAO Yihang

left_side:
  background_image: "./background.jpg"

menu:

  - text: Home
    link: /index
    icon: ""
    
    
  - text: Publications
    link: /publications
    icon: ""

  - text: Research Experience
    link: /research_experience
    icon: ""

  - text: Teaching Experience
    link: /teaching_experience
    icon: ""
    
  - text: Honors & Awards
    link: /honors_awards
    icon: ""
    
  - text: Colourful Life
    link: /life/colourful_life
    icon: ""
  
